### PR TITLE
Fix PHP unit test failure

### PR DESCRIPTION
**Pull request by ScottVerbeek**
…it\Framework\TestCase::setUp(): void

### CODE REVIEW

**Comment by ScottVerbeek** [comment]
Failing tests are linked to PHPDoc which is solved here 
https://github.com/catalyst/moodle-local_envbar/pull/151

**Comment by dmitriim** [comment]
Can we create MR for master as well please?

**Comment by ScottVerbeek** [comment]
I can create a MR for PHPDoc for master. I think adding this commit will cause drop of support.

**Comment by ScottVerbeek** [comment]
@dmitriim I have created this pull request https://github.com/catalyst/moodle-local_envbar/pull/152 for master branch with master-phpdoc.

**Comment by ScottVerbeek** [comment]
Duo to branch naming conventions this branch should no longer be used.

**Pull request closed without merging**
